apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: word-picker
parameters: 
- name: APP_POSTFIX
  description: This postfix is appende to every name and tag.
  required: true
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: word-picker-options-${APP_POSTFIX}
    namespace: word-picker-a-lz
  data:
    custom_options.txt:  |
      alpha